language: node_js
node_js:
- '5'
services:
- mongodb
script:
- npm run test
after_script:
- npm install coveralls && cat ./coverage/lcov.info | coveralls
deploy:
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_02ebef9cfc9c_key -iv $encrypted_02ebef9cfc9c_iv
  -in deploy-key.enc -out deploy-key -d
after_success:
  - echo -e "Host 159.203.223.225\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh bygis@159.203.223.225
