language: node_js
node_js:
  - '4.4.4'
services:
  - mongodb
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise
    packages:
      - g++-4.9
      - mongodb-org-server
      - graphicsmagick
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_02ebef9cfc9c_key -iv $encrypted_02ebef9cfc9c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
  - npm run test
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host bygis.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd ..
  - tar -jcf judy.tar.bz2 judy
  - scp judy.tar.bz2 bygis@bygis.com:~/
  - ssh bygis@bygis.com 'tar -jxf judy.tar.bz2'
  - cd judy
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
